# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 11:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AddField(
            model_name='forum',
            name='section',
            field=models.ForeignKey(default=146728754, on_delete=django.db.models.deletion.CASCADE, to='forum.Section'),
            preserve_default=False,
        ),
    ]
