# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20160530_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='order_in',
            field=models.IntegerField(default=1),
        ),
    ]
