# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_section_order_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='order_in',
        ),
    ]
