# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_remove_section_order_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
