# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20160616_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
