# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 08:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_forum_closed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forum',
            options={'permissions': (('can_lock_forum', 'Can change forum lock status'), ('can_post_lock_forum', 'Can post in locked forums'))},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'permissions': (('can_close_topic', 'Can change topic closed status'), ('can_pin_topic', 'Can change topic pinned status'))},
        ),
    ]
