# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-06 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_auto_20160706_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
