# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 16:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='created',
        ),
        migrations.AddField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 1, 16, 58, 52, 123338, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
