# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
