# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_auto_20160606_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='/static/images/avatar_blank.png', upload_to='profile_images'),
            preserve_default=False,
        ),
    ]
