# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(help_text='IP address or IP network', max_length=18, verbose_name='IP network')),
            ],
            options={
                'verbose_name_plural': 'Allowed IPs',
                'verbose_name': 'Allowed IP',
            },
        ),
        migrations.CreateModel(
            name='DeniedIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(help_text='IP address or IP network', max_length=18, verbose_name='IP network')),
            ],
            options={
                'verbose_name_plural': 'Denied IPs',
                'verbose_name': 'Denied IP',
            },
        ),
    ]
